[package]
name = "solana-ristretto"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.4.0"
solana-zk-token-sdk = "1.17.17"

[target.'cfg(not(target_os = "solana"))'.dependencies]
curve25519-dalek = "3.2.1"
digest = { version="0.10", default-features=false, optional=true}
